<?php
/**
 * @file
 * Delete webform multiple submissions.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ajax_privatemsg_form_privatemsg_new_alter(&$form, &$form_state, $form_id) {
	$form['actions']['submit']['#ajax'] = array(
		'callback' => 'ajax_privatemsg_ajax_callback',
		'wrapper' => 'privatemsg-new',
	);
}

/**
 * callback for ajax submit().
 */
function ajax_privatemsg_ajax_callback($form, $form_state) {
  $form['subject']['#value'] = '';
  $form['body']['value']['#value'] = '';
  $form['recipient']['#value'] = '';
  return $form;
}
